apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: alpine:3.12
    name: test-container
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#claims-as-volumes
      claimName: pv-claim-demo
      readonly: true
