# Run
#   pre-commit install
repos:
 - repo: https://github.com/yuvipanda/pre-commit-hook-ensure-sops
   rev: v1.0
   hooks:
     - id: sops-encryption
       # Uncomment to exclude all markdown files from encryption
       # exclude: *.\.md
