apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - soft
    - noatime
    - vers=4.2
  nfs:
    # FIXED: Use internal DNS name
    server: nfs-server.${NAMESPACE}.svc.cluster.local
    path: "${DATA_PATH}"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-data
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
