apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${NFS_PV_NAME}
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ${NFS_ACCESS_MODE}
  mountOptions:
    - soft
    - noatime
    - vers=4.2
  nfs:
    # Use internal DNS name
    server: nfs-server.${NAMESPACE}.svc.cluster.local
    path: "${NFS_DISK_PATH}"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${NFS_PV_NAME}
spec:
  accessModes:
    - ${NFS_ACCESS_MODE}
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
